### ISSUE TITLE
Add status for orders-products

### ISSUE THREAD

**Issue by carlosero** [carlosero/order_tree#3]
We need to know what products are done and what products aren't inside an order.

**Comment by pragmacarlos** [comment]
Views:
Orders#show
Orders#index (show amount of completed items)

**Comment by carlosero** [comment]
* Add percentage for orders completion
* Add delivery date for orders-products

**Comment by carlosero** [comment]
Status added. 2d543e9580014d19025863351801e6c36e9fe5be
